const ACTION_TYPES = {
  SELECT_NODE_TYPE: 'SELECT_NODE_TYPE',
  SELECT_NEW_NODE_TYPE: 'SELECT_NEW_NODE_TYPE',
  ADD_SELECTED_NODE: 'ADD_NODE',
  CONNECT_NODE: 'CONNECT_NODE',
  REMOVE_CONNECTED_NODE: 'REMOVE_CONNECTED_NODE',
  UPDATE_NODE: 'UPDATE_NODE',
  SHOW_MODAL: 'SHOW_MODAL',
  CANCEL_MODAL: 'CANCEL_MODAL',

  GET_OPTIONS: 'GET_OPTIONS',
  GET_OPTIONS_SUCCESS: 'GET_OPTIONS_SUCCESS',
  GET_OPTIONS_FAILURE: 'GET_OPTIONS_FAILURE'
};

export default ACTION_TYPES;