const ACTION_TYPES = {
  SELECT_SEARCH_NODE_TYPE: 'SELECT_SEARCH_NODE_TYPE',
  ON_CHANGE_SEARCH_VALUE: 'ON_CHANGE_SEARCH_VALUE',
  ON_SUBMIT_SEARCH: 'ON_SUBMIT_SEARCH',
  SELECT_LIST_SIZE: 'SELECT_LIST_SIZE',
  SHOW_SEARCH_NODE_INFO: 'SHOW_SEARCH_NODE_INFO',
  START_NEW_SEARCH: 'START_NEW_SEARCH',
  SELECT_SEARCH_NODE_EDGES: 'SELECT_SEARCH_NODE_EDGES',
  ESCAPE_MODAL: 'ESCAPE_MODAL',

  ON_SUBMIT_SEARCH_SUCCESS: 'ON_SUBMIT_SEARCH_SUCCESS',
  ON_SUBMIT_SEARCH_FAILURE: 'ON_SUBMIT_SEARCH_FAILURE',

  ON_NODE_EDGES_SELECT: 'ON_NODE_EDGES_SELECT',
  ON_NODE_EDGES_SELECT_SUCCESS: 'ON_SEARCH_NODE_EDGES_SUCCESS',
  ON_NODE_EDGES_SELECT_FAILURE: 'ON_SEARCH_NODE_EDGES_FAILURE',

  GET_EDGE_TYPES: 'GET_EDGE_TYPES',
  GET_EDGE_TYPES_SUCCESS: 'GET_EDGE_TYPES_SUCCESS',
  GET_EDGE_TYPES_FAILURE: 'GET_EDGE_TYPES_FAILURE',

  GET_VOCABULARY_TYPES: 'GET_VOCABULARY_TYPES',
  GET_VOCABULARY_TYPES_SUCCESS: 'GET_VOCABULARY_TYPES_SUCCESS',
  GET_VOCABULARY_TYPES_FAILURE: 'GET_VOCABULARY_TYPES_FAILURE' 
};

export default ACTION_TYPES;