export const header: string;
export const candidate: string;
export const link: string;
export const avatar: string;
export const name: string;
export const location: string;
export const textLabel: string;
export const contactInfo: string;
export const controls: string;
